### PR TITLE
Add primitive defs for kintexuplus

### PR DESCRIPTION
**Pull request by bonddenhalter**
There may be some issues with the way these were created in VSRT, because I had to make a few edits in the FamilyInfo file (adding HARD0GND bels to SLICEL and SLICEM sites), but aside from that they are correct and successfully installed in RapidSmith2. #3

### CODE REVIEW

**Review by bradselw — APPROVED** [review]
I would just like to point out that we don't have any good way to test changes like these, so all testing will have to be done manually. Please make sure you test out functions such as [`sites::get_site_wire_sinks`](http://byuccl.github.io/tincr/namespacetincr_1_1sites.html#a82da3418178a0be9234cf4e227ab8688) that consume the .def files for this part.

**Comment by xrtc** [comment]
I would like to know in more detail why the familyInfo file had to be hand edited.  Is this something that will happen in the future or was there a problem just this time that required it?  If it can be avoided in the future, has the method for doing so been documented?  I view this as extremely important to document.

**Comment by bonddenhalter** [comment]
I'm not very experienced with Tincr. Could you give me some example code I
could run to test out that function? I'm not sure how to obtain a source
object to give it as a parameter.

**Comment by bonddenhalter** [comment]
@bradselw I'm not very experienced with Tincr. Could you give me some example code I could run to test out that function? I'm not sure how to obtain a source object to give it as a parameter.

**Comment by ttown523** [comment]
Dr. Nelson,

If you go through the entire process from scratch, the only hand edits for the family info file are adding a few compatible sites manually (two for UltraScale). Bond didn't need to add the new BELs manually, he could have created a new "addedBels.txt" file and added that file as a parameter to the "create_xml_family_info" function. As we stated in our previous meeting, for UltraScale devices there were no significant hand edits. This is also most likely true for UltraScale+, but we still have to do further device testing to ensure this.

**Pull request merged**
